### PR TITLE
Ritam

### PR DESCRIPTION
**Pull request by RitamChakraborty**
Made some changes. Do check if you find time.

### CODE REVIEW

**Comment by shatanikmahanty** [comment]
@RitamChakraborty Can you pull the current files and make a pull request again. I added CMake to the project. Sorry for the late reply didn't open GitHub for a long time

**Comment by shatanikmahanty** [comment]
Great work btw. :fire::fire::fire::fire:

**Comment by RitamChakraborty** [comment]
> Great work btw.

😂, I used an api to get the data in JavaScript. Then console logged the C++ code as output. Please don't think I tried to push you to merge my pr. I was just joking.

**Comment by RitamChakraborty** [comment]
I changed the start of the application from `PeriodicFile.cpp` to `main.cpp`. It looks right to me. Let me know, if you want me to go with the previous one. 

Another thing, I don't have **3.19** version of *CMake*, I have gone with **3.13**. Hope that will not be that big of an issue. I can't update to the latest version. And the reason is of the scope of this conversation I guesss. :neutral_face:

**Comment by shatanikmahanty** [comment]
Yeah main.cpp is ok

**Pull request merged**
